import { getServiceRoleClient } from '@/lib/supabase';
import { verifyAdminSession } from '@/lib/admin-auth';
import { NextRequest, NextResponse } from 'next/server';
import crypto from 'crypto';

/**
 * Generates a secure random token for claim links.
 * Uses crypto.randomBytes for cryptographic security.
 */
function generateSecureToken(): string {
  const bytes = crypto.randomBytes(32);
  return bytes
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

// Safety-net expiry: admin links default to 60 days. Callers may override with
// expiresInDays (a positive number), or pass expiresInDays: null for a
// non-expiring link.
const DEFAULT_EXPIRES_IN_DAYS = 60;

/**
 * Admin endpoint to generate magic claim links.
 * POST /api/admin/generate-claim-link
 *
 * Request body (optional): { expiresInDays?: number | null }
 */
export async function POST(req: NextRequest) {
  try {
    // Verify admin access (signed session — not a forgeable header).
    const session = await verifyAdminSession();
    if (!session?.authenticated) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized: Admin access required' },
        { status: 401 }
      );
    }
    const adminEmail = session.email || 'unknown';

    const body = await req.json().catch(() => ({}));

    let expiresAt: string | null;
    if (body.expiresInDays === null) {
      expiresAt = null;
    } else {
      const requested = Number(body.expiresInDays);
      const days = Number.isFinite(requested) && requested > 0 ? requested : DEFAULT_EXPIRES_IN_DAYS;
      expiresAt = new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
    }

    const token = generateSecureToken();
    const supabase = getServiceRoleClient();

    const { data: claimLink, error: insertError } = await supabase
      .from('free_event_claims')
      .insert([
        {
          token,
          claimed: false,
          created_by_admin_email: adminEmail,
          expires_at: expiresAt,
        },
      ])
      .select()
      .single();

    if (insertError) {
      console.error('Error creating claim link:', insertError);
      return NextResponse.json(
        { success: false, error: 'Failed to create claim link in database' },
        { status: 500 }
      );
    }

    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://snapworxx.com';
    const claimUrl = `${baseUrl}/claim/${token}`;

    console.log(`✅ Magic link generated by ${adminEmail}: ${claimUrl}`);

    return NextResponse.json({
      success: true,
      data: {
        id: claimLink.id,
        token: claimLink.token,
        claimUrl,
        expiresAt,
        createdAt: claimLink.created_at,
      },
    });
  } catch (err) {
    console.error('Unhandled error in generate-claim-link:', err);
    return NextResponse.json(
      { success: false, error: 'Server error', details: String(err) },
      { status: 500 }
    );
  }
}
