import { getServiceRoleClient } from '@/lib/supabase';
import { NextRequest, NextResponse } from 'next/server';
import crypto from 'crypto';

/**
 * Generates a secure random token for claim links
 * Uses crypto.randomBytes for cryptographic security
 */
function generateSecureToken(): string {
  // Generate 32 random bytes and convert to URL-safe base64
  const bytes = crypto.randomBytes(32);
  return bytes
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

/**
 * Check if request is from authenticated admin
 */
function isAdminRequest(request: Request | NextRequest): boolean {
  const cookieHeader = request.headers.get('cookie');
  if (cookieHeader) {
    const cookies = cookieHeader.split('; ');
    const adminSessionCookie = cookies.find(c => c.startsWith('admin_session='));
    if (adminSessionCookie) return true;
  }

  const authHeader = request.headers.get('authorization');
  if (authHeader?.startsWith('Bearer admin_')) return true;

  return false;
}

/**
 * Admin endpoint to generate magic claim links
 * POST /api/admin/generate-claim-link
 *
 * Request body (optional):
 * {
 *   expiresInDays?: number (default 30)
 * }
 *
 * Response:
 * {
 *   success: true,
 *   data: {
 *     token: string,
 *     claimUrl: string,
 *     expiresAt: string | null,
 *     createdAt: string
 *   }
 * }
 */
export async function POST(req: NextRequest) {
  try {
    // Verify admin access
    if (!isAdminRequest(req)) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized: Admin access required' },
        { status: 401 }
      );
    }

    // Get admin email from cookies for tracking
    const cookieHeader = req.headers.get('cookie');
    let adminEmail = 'unknown';
    if (cookieHeader) {
      const cookies = cookieHeader.split('; ');
      const emailCookie = cookies.find(c => c.startsWith('admin_email='));
      if (emailCookie) {
        adminEmail = decodeURIComponent(emailCookie.split('=')[1]);
      }
    }

    // Parse request body (optional parameters)
    const body = await req.json().catch(() => ({}));

    // Generate secure token
    const token = generateSecureToken();

    // Get Supabase client
    const supabase = getServiceRoleClient();

    // Insert claim link into database (no expiration)
    const { data: claimLink, error: insertError } = await supabase
      .from('free_event_claims')
      .insert([
        {
          token,
          claimed: false,
          created_by_admin_email: adminEmail,
          expires_at: null, // No expiration
        },
      ])
      .select()
      .single();

    if (insertError) {
      console.error('Error creating claim link:', insertError);
      return NextResponse.json(
        { success: false, error: 'Failed to create claim link in database' },
        { status: 500 }
      );
    }

    // Generate claim URL
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://snapworxx.com';
    const claimUrl = `${baseUrl}/claim/${token}`;

    console.log(`✅ Magic link generated by ${adminEmail}: ${claimUrl}`);

    return NextResponse.json({
      success: true,
      data: {
        id: claimLink.id,
        token: claimLink.token,
        claimUrl,
        expiresAt: null,
        createdAt: claimLink.created_at,
      },
    });
  } catch (err) {
    console.error('Unhandled error in generate-claim-link:', err);
    return NextResponse.json(
      { success: false, error: 'Server error', details: String(err) },
      { status: 500 }
    );
  }
}
