import { NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';
import { supabase } from '@/lib/supabase';

export async function POST(request: NextRequest) {
  try {
    const { 
      eventName, 
      eventDate, 
      emailAddress, 
      yourName, 
      package: selectedPackage, 
      price,
      discountCode,
      validateOnly,
      isAffiliateReferral 
    } = await request.json();

    if (!eventName || !emailAddress) {
      return NextResponse.json(
        { error: 'Event name and email address are required' },
        { status: 400 }
      );
    }

    const stripeSecretKey = process.env.STRIPE_SECRET_KEY;
    
    // Check if Stripe is properly configured
    if (!stripeSecretKey || stripeSecretKey === 'sk_test_your-stripe-secret-key') {
      console.log('Stripe not configured, returning mock success URL');
      // Return a mock success URL for development
      return NextResponse.json({ 
        sessionId: 'mock_session_id',
        url: `${process.env.NEXT_PUBLIC_APP_URL}/success?session_id=mock_session_id&mock=true`
      });
    }

    const stripe = new Stripe(stripeSecretKey, {
      apiVersion: '2025-10-29.clover',
    });

    const packageName = selectedPackage === 'premium' ? 'Premium Package' : 'Basic Package';
    let packagePrice = price || (selectedPackage === 'premium' ? 4900 : 2900);
    let discountPercent = 0;
    let validDiscountCode = null;

    let affiliateInfo = null;

    // Validate discount code if provided
    if (discountCode && discountCode.trim()) {
      const trimmedCode = discountCode.trim().toUpperCase();
      
      // Check if it's an affiliate referral code first
      if (isAffiliateReferral) {
        try {
          const { data: affiliate } = await supabase
            .from('affiliates')
            .select('id, name, email, referral_code, commission_rate, status')
            .eq('referral_code', trimmedCode)
            .eq('status', 'active')
            .single();

          if (affiliate) {
            discountPercent = 10; // Affiliate referrals get 10% discount
            validDiscountCode = trimmedCode;
            packagePrice = Math.round(packagePrice * (1 - discountPercent / 100));
            affiliateInfo = affiliate;
          }
        } catch (error) {
          console.error('Error validating affiliate code:', error);
        }
      }
      
      // If not an affiliate code or affiliate lookup failed, try regular discount codes
      if (!affiliateInfo) {
        const validCodes: Record<string, number> = {
          'LAUNCH50': 50,
          'EARLY30': 30,
          'WELCOME25': 25,
          'FRIEND20': 20,
          'SAVE15': 15
        };
        
        // Also accept any WELCOME prefix codes (generated by email flow) as 30% off
        const isWelcomeCode = trimmedCode.startsWith('WELCOME') && trimmedCode.length === 11;
        
        if (validCodes[trimmedCode]) {
          discountPercent = validCodes[trimmedCode];
          validDiscountCode = trimmedCode;
          packagePrice = Math.round(packagePrice * (1 - discountPercent / 100));
        } else if (isWelcomeCode) {
          discountPercent = 30; // WELCOME codes get 30% off
          validDiscountCode = trimmedCode;
          packagePrice = Math.round(packagePrice * (1 - discountPercent / 100));
        } else {
          return NextResponse.json(
            { error: 'Invalid discount code. Please check your code and try again.' },
            { status: 400 }
          );
        }
      }
    }

    // If this is just for validation, return the discount info
    if (validateOnly) {
      return NextResponse.json({
        discountApplied: discountPercent > 0,
        discountPercent,
        finalPrice: packagePrice,
        validCode: validDiscountCode
      });
    }

    // Prepare line items for Stripe
    const lineItems = [
      {
        price_data: {
          currency: 'usd',
          product_data: {
            name: `SnapWorxx ${packageName}`,
            description: `Event: ${eventName}${discountPercent > 0 ? ` (${discountPercent}% discount applied)` : ''}`,
          },
          unit_amount: packagePrice,
        },
        quantity: 1,
      }
    ];

    // Create Stripe checkout session
    const sessionConfig: any = {
      payment_method_types: ['card'],
      line_items: lineItems,
      mode: 'payment',
      success_url: `${process.env.NEXT_PUBLIC_APP_URL}/success?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${process.env.NEXT_PUBLIC_APP_URL}/create`,
      customer_email: emailAddress,
      allow_promotion_codes: true, // Enable customers to enter Stripe promotion codes
      metadata: {
        eventName,
        eventDate: eventDate || '',
        emailAddress,
        yourName: yourName || '',
        package: selectedPackage,
        discountCode: validDiscountCode || '',
        discountPercent: discountPercent.toString(),
        affiliateId: affiliateInfo?.id || '',
        affiliateReferralCode: affiliateInfo?.referral_code || '',
        isAffiliateReferral: isAffiliateReferral ? 'true' : 'false',
      },
    };

    console.log('Creating Stripe session with allow_promotion_codes:', sessionConfig.allow_promotion_codes);

    const session = await stripe.checkout.sessions.create(sessionConfig);
    
    console.log('Session created:', {
      id: session.id,
      url: session.url,
      allow_promotion_codes: (session as any).allow_promotion_codes
    });

    return NextResponse.json({ 
      sessionId: session.id, 
      url: session.url,
      discountApplied: discountPercent > 0,
      discountPercent,
      finalPrice: packagePrice
    });
  } catch (error) {
    console.error('Error creating checkout session:', error);
    
    // Provide more detailed error information
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    
    return NextResponse.json(
      { 
        error: 'Failed to create checkout session',
        details: errorMessage,
        hint: 'Make sure your Stripe secret key is properly configured in environment variables'
      },
      { status: 500 }
    );
  }
}
